const CT = {
  EMPTY: 0,

  // Walls
  BRICK_WALL: 1,
  CONCRETE_WALL: 2,
  WHITE_WALL: 3,
  FENCE: 4,
  FENCE_GRASS: 5,
  FENCE_BAMBOO: 6,
  PERIMETER_WALL: 7,
  BARRED_WALL: 8,
  TILED_WALL: 9,
  YUTANI_WALL: 10,
  RUSTY_WALL: 11,
  SLUM_WALL: 12,
  DERELICT_WALL: 13,
  OVERGROWN_WALL: 14,
  ART_DECO_WALL: 15,
  HEDGE: 16,
  CUSHIONED_WALL: 17,
  CLASSY_BURGUNDY: 18,
  ORIENTAL_WALL: 19,
  CLASSY_GREEN: 20,
  CLASSY_BLUE: 21,
  DECAYED_WALL: 22,
  MIN_SEC_WALL: 23,
  MED_SEC_WALL: 24,
  MAX_SEC_WALL: 25,
  WHITE_SEC_WALL: 26,
  YELLOW_WALL: 27,
  CLIFF_EDGE_WALL: 28,
  RECLAIMED_WOOD: 29,
  BOTTLE_WALL: 30,
  WHITE_PICKET: 31,
  HAY_BALE: 32,
  WOODEN_FENCE: 33,
  GARDEN_WALL: 34,
  DOOR: 35,
  STAFF_DOOR: 36,
  DOUBLE_DOOR: 37,
  SECURE_DOOR: 38,
  BLUE_DOOR: 39,
  RED_DOOR: 40,
  DOUBLE_DOOR_R: 41,
  ORANGE_DOOR: 42,
  DOUBLE_STAFF_DOOR: 43,
  DOUBLE_STAFF_DOOR_R: 44,
  HOUSE_DOOR: 45,
  HOUSE_DOOR_R: 46,

  // Indoor Floors
  CONCRETE_FLOOR: 50,
  WOODEN_FLOOR: 51,
  CHECKERED_FLOOR: 52,
  METAL_FLOOR: 53,
  CARGO_FLOOR: 54,
  CARPET_RED: 55,
  WHITE_TILES: 56,
  MARBLE_TILES: 57,
  GRATE_FLOOR: 58,
  IRON_FLOOR: 59,
  CERAMIC_FLOOR: 60,
  MOSAIC_FLOOR: 61,
  FANCY_TILES: 62,
  CARPET_BLUE: 63,
  CARPET_BROWN: 64,
  PADDED: 65,
  SOLACO: 66,
  CONCRETE_TILE: 67,
  LIMESTONE: 68,
  BAMBOO_FLOOR: 69,
  LAMINATE: 70,
  CARPET: 71,
  RECLAIMED_BRICK: 72,
  RECLAIMED_RUBBER: 73,

  // Outdoor Floors
  GRASS: 100,
  DIRT: 101,
  GRAVEL: 102,
  PAVING_STONE: 103,
  SAND: 104,
  ROAD: 105,
  STONE: 106,
  SANDSTONE: 107,
  MUD: 108,
  GRASS_CORNER: 109,
  GRASS_N_STONES: 110,
  LUNAR: 111,
  SNOW: 112,
  RUNNING_TRACK: 113,
  FLOWERY_FIELD: 114,
  DOCK_WOODEN: 115,
  CLIFF_EDGE_FLOOR: 116,
  FIELD_GRASS: 117,
  WATER: 118,
};

// Range helpers: cells 1-46 walls/doors, 50-73 indoor floors, 100-118 outdoor floors.
CT.isWall = c => c >= 1 && c <= 35;
CT.isIndoor = c => c >= 50 && c <= 73;
CT.isOutdoor = c => c >= 100 && c <= 118;

// Keep CellTypes as alias for backward compat
const CellTypes = CT;

const WallVariantPrefix = {
  [CT.CONCRETE_WALL]: 'cw',
  [CT.BRICK_WALL]: 'bw',
  [CT.WHITE_WALL]: 'ww',
  [CT.FENCE]: 'fn',
  [CT.FENCE_GRASS]: 'fgw',
  [CT.FENCE_BAMBOO]: 'fbw',
  [CT.PERIMETER_WALL]: 'pw',
  [CT.BARRED_WALL]: 'baw',
  [CT.TILED_WALL]: 'tw',
  [CT.YUTANI_WALL]: 'yut',
  [CT.RUSTY_WALL]: 'rw',
  [CT.SLUM_WALL]: 'slw',
  [CT.DERELICT_WALL]: 'dlw',
  [CT.OVERGROWN_WALL]: 'ogw',
  [CT.ART_DECO_WALL]: 'adw',
  [CT.HEDGE]: 'hw',
  [CT.CUSHIONED_WALL]: 'csw',
  [CT.CLASSY_BURGUNDY]: 'cbw',
  [CT.ORIENTAL_WALL]: 'orw',
  [CT.CLASSY_GREEN]: 'cgw',
  [CT.CLASSY_BLUE]: 'cbl',
  [CT.DECAYED_WALL]: 'dcw',
  [CT.MIN_SEC_WALL]: 'mnw',
  [CT.MED_SEC_WALL]: 'mdw',
  [CT.MAX_SEC_WALL]: 'mxw',
  [CT.WHITE_SEC_WALL]: 'wsw',
  [CT.YELLOW_WALL]: 'ylw',
  [CT.RECLAIMED_WOOD]: 'rcw',
  [CT.BOTTLE_WALL]: 'btw',
  [CT.WHITE_PICKET]: 'wpf',
  [CT.HAY_BALE]: 'hbw',
  [CT.WOODEN_FENCE]: 'wnf',
  [CT.GARDEN_WALL]: 'gdw',
};

// Map cell type ID → texture name (key in Textures.manifest)
const CellTextures = {
  [CT.BRICK_WALL]: 'brick_wall',
  [CT.CONCRETE_WALL]: 'concrete_wall',
  [CT.WHITE_WALL]: 'white_wall',
  [CT.FENCE]: 'fence',
  [CT.FENCE_GRASS]: 'fence_grass',
  [CT.FENCE_BAMBOO]: 'fence_bamboo',
  [CT.PERIMETER_WALL]: 'perimeter_wall',
  [CT.BARRED_WALL]: 'barred_wall',
  [CT.TILED_WALL]: 'tiled_wall',
  [CT.YUTANI_WALL]: 'yutani_wall',
  [CT.RUSTY_WALL]: 'rusty_wall',
  [CT.SLUM_WALL]: 'slum_wall',
  [CT.DERELICT_WALL]: 'derelict_wall',
  [CT.OVERGROWN_WALL]: 'overgrown_wall',
  [CT.ART_DECO_WALL]: 'art_deco_wall',
  [CT.HEDGE]: 'hedge',
  [CT.CUSHIONED_WALL]: 'cushioned_wall',
  [CT.CLASSY_BURGUNDY]: 'classy_burgundy',
  [CT.ORIENTAL_WALL]: 'oriental_wall',
  [CT.CLASSY_GREEN]: 'classy_green',
  [CT.CLASSY_BLUE]: 'classy_blue',
  [CT.DECAYED_WALL]: 'decayed_wall',
  [CT.MIN_SEC_WALL]: 'min_sec_wall',
  [CT.MED_SEC_WALL]: 'med_sec_wall',
  [CT.MAX_SEC_WALL]: 'max_sec_wall',
  [CT.WHITE_SEC_WALL]: 'white_sec_wall',
  [CT.YELLOW_WALL]: 'yellow_wall',
  [CT.CLIFF_EDGE_WALL]: 'cliff_edge_wall',
  [CT.RECLAIMED_WOOD]: 'reclaimed_wood',
  [CT.BOTTLE_WALL]: 'bottle_wall',
  [CT.WHITE_PICKET]: 'white_picket',
  [CT.HAY_BALE]: 'hay_bale',
  [CT.WOODEN_FENCE]: 'wooden_fence',
  [CT.GARDEN_WALL]: 'garden_wall',
  [CT.DOOR]: 'door',
  [CT.STAFF_DOOR]: 'staff_door',
  [CT.DOUBLE_DOOR]: 'double_door_l',
  [CT.DOUBLE_DOOR_R]: 'double_door_r',
  [CT.SECURE_DOOR]: 'secure_door',
  [CT.BLUE_DOOR]: 'blue_door',
  [CT.RED_DOOR]: 'red_door',
  [CT.ORANGE_DOOR]: 'orange_door',
  [CT.DOUBLE_STAFF_DOOR]: 'double_staff_door_l',
  [CT.DOUBLE_STAFF_DOOR_R]: 'double_staff_door_r',
  [CT.HOUSE_DOOR]: 'house_door_l',
  [CT.HOUSE_DOOR_R]: 'house_door_r',

  [CT.CONCRETE_FLOOR]: 'concrete_floor',
  [CT.WOODEN_FLOOR]: 'wooden_floor',
  [CT.CHECKERED_FLOOR]: 'checkered_floor',
  [CT.METAL_FLOOR]: 'metal_floor',
  [CT.CARGO_FLOOR]: 'cargo_floor',
  [CT.CARPET_RED]: 'carpet_red',
  [CT.WHITE_TILES]: 'white_tiles',
  [CT.MARBLE_TILES]: 'marble_tiles',
  [CT.GRATE_FLOOR]: 'grate_floor',
  [CT.IRON_FLOOR]: 'iron_floor',
  [CT.CERAMIC_FLOOR]: 'ceramic_floor',
  [CT.MOSAIC_FLOOR]: 'mosaic_floor',
  [CT.FANCY_TILES]: 'fancy_tiles',
  [CT.CARPET_BLUE]: 'carpet_blue',
  [CT.CARPET_BROWN]: 'carpet_brown',
  [CT.PADDED]: 'padded',
  [CT.SOLACO]: 'solaco',
  [CT.CONCRETE_TILE]: 'concrete_tile',
  [CT.LIMESTONE]: 'limestone',
  [CT.BAMBOO_FLOOR]: 'bamboo_floor',
  [CT.LAMINATE]: 'laminate',
  [CT.CARPET]: 'carpet',
  [CT.RECLAIMED_BRICK]: 'reclaimed_brick',
  [CT.RECLAIMED_RUBBER]: 'reclaimed_rubber',

  [CT.GRASS]: 'grass',
  [CT.DIRT]: 'dirt',
  [CT.GRAVEL]: 'gravel',
  [CT.PAVING_STONE]: 'paving_stone',
  [CT.SAND]: 'sand',
  [CT.ROAD]: 'road',
  [CT.STONE]: 'stone',
  [CT.SANDSTONE]: 'sandstone',
  [CT.MUD]: 'mud',
  [CT.GRASS_CORNER]: 'grass_corner',
  [CT.GRASS_N_STONES]: 'grass_n_stones',
  [CT.LUNAR]: 'lunar',
  [CT.SNOW]: 'snow',
  [CT.RUNNING_TRACK]: 'running_track',
  [CT.FLOWERY_FIELD]: 'flowery_field',
  [CT.DOCK_WOODEN]: 'dock_wooden',
  [CT.CLIFF_EDGE_FLOOR]: 'cliff_edge_floor',
  [CT.FIELD_GRASS]: 'field_grass',
  [CT.WATER]: 'water',
};

// Minimap fallback colors (sampled from textures)
const CellMinimapColors = {
  [CT.BRICK_WALL]: '#8B5E3C', [CT.CONCRETE_WALL]: '#707070', [CT.WHITE_WALL]: '#D0D0D0',
  [CT.FENCE]: '#888', [CT.FENCE_GRASS]: '#7A8', [CT.FENCE_BAMBOO]: '#9A7',
  [CT.PERIMETER_WALL]: '#4A4A4A', [CT.BARRED_WALL]: '#666', [CT.TILED_WALL]: '#AAA',
  [CT.YUTANI_WALL]: '#404855', [CT.RUSTY_WALL]: '#8B5533', [CT.SLUM_WALL]: '#6A6A5A',
  [CT.DERELICT_WALL]: '#7A7A6A', [CT.OVERGROWN_WALL]: '#5A7A4A', [CT.ART_DECO_WALL]: '#8A7A5A',
  [CT.HEDGE]: '#4A7A3A', [CT.CUSHIONED_WALL]: '#8A6A5A', [CT.CLASSY_BURGUNDY]: '#7A3A3A',
  [CT.ORIENTAL_WALL]: '#6A5A4A', [CT.CLASSY_GREEN]: '#3A6A3A', [CT.CLASSY_BLUE]: '#3A4A7A',
  [CT.DECAYED_WALL]: '#8A8A7A', [CT.MIN_SEC_WALL]: '#4A7AAA', [CT.MED_SEC_WALL]: '#DA8A2A',
  [CT.MAX_SEC_WALL]: '#DA4A2A', [CT.WHITE_SEC_WALL]: '#DADADA', [CT.YELLOW_WALL]: '#DAC04A',
  [CT.CLIFF_EDGE_WALL]: '#5A5040', [CT.RECLAIMED_WOOD]: '#7A6A4A', [CT.BOTTLE_WALL]: '#5A8A5A',
  [CT.WHITE_PICKET]: '#E0E0E0', [CT.HAY_BALE]: '#C0A050', [CT.WOODEN_FENCE]: '#8A6A3A',
  [CT.GARDEN_WALL]: '#6A6A5A', [CT.DOOR]: '#8B7355',
  [CT.STAFF_DOOR]: '#4A8A4A', [CT.DOUBLE_DOOR]: '#C0943A', [CT.SECURE_DOOR]: '#6A6A6A',
  [CT.BLUE_DOOR]: '#3A5A9A', [CT.RED_DOOR]: '#9A3A3A', [CT.DOUBLE_DOOR_R]: '#C0943A',
  [CT.ORANGE_DOOR]: '#DA7A2A', [CT.DOUBLE_STAFF_DOOR]: '#4A8A4A', [CT.DOUBLE_STAFF_DOOR_R]: '#4A8A4A',
  [CT.HOUSE_DOOR]: '#8B6A3A', [CT.HOUSE_DOOR_R]: '#8B6A3A',

  [CT.CONCRETE_FLOOR]: '#A8A8A0', [CT.WOODEN_FLOOR]: '#B8935A', [CT.CHECKERED_FLOOR]: '#909090',
  [CT.METAL_FLOOR]: '#606468', [CT.CARGO_FLOOR]: '#5A5E62', [CT.CARPET_RED]: '#8B4040',
  [CT.WHITE_TILES]: '#E0E0DD', [CT.MARBLE_TILES]: '#D5D0C8', [CT.GRATE_FLOOR]: '#444',
  [CT.IRON_FLOOR]: '#555', [CT.CERAMIC_FLOOR]: '#C0B8A0', [CT.MOSAIC_FLOOR]: '#9A8A6A',
  [CT.FANCY_TILES]: '#B0A090', [CT.CARPET_BLUE]: '#4A5A8A', [CT.CARPET_BROWN]: '#7A6A5A',
  [CT.PADDED]: '#AAAAAA', [CT.SOLACO]: '#3A4A5A', [CT.CONCRETE_TILE]: '#999',
  [CT.LIMESTONE]: '#C0B8A0', [CT.BAMBOO_FLOOR]: '#8A9A5A', [CT.LAMINATE]: '#A09070',
  [CT.CARPET]: '#7A5A4A', [CT.RECLAIMED_BRICK]: '#8A5A3A', [CT.RECLAIMED_RUBBER]: '#4A4A4A',

  [CT.GRASS]: '#5A8C3A', [CT.DIRT]: '#8B7355', [CT.GRAVEL]: '#A09888',
  [CT.PAVING_STONE]: '#909090', [CT.SAND]: '#D4C090', [CT.ROAD]: '#505050',
  [CT.STONE]: '#808080', [CT.SANDSTONE]: '#C0A878', [CT.MUD]: '#6A5A3A',
  [CT.GRASS_CORNER]: '#5A8C3A', [CT.GRASS_N_STONES]: '#7A9A6A', [CT.LUNAR]: '#707070',
  [CT.SNOW]: '#E8E8F0', [CT.RUNNING_TRACK]: '#AA5533', [CT.FLOWERY_FIELD]: '#6A9A5A',
  [CT.DOCK_WOODEN]: '#9A7A4A', [CT.CLIFF_EDGE_FLOOR]: '#5A5040', [CT.FIELD_GRASS]: '#5A8A3A',
  [CT.WATER]: '#3A6AAA',
};
