// Desk types that operational workers can claim
const DESK_TYPES = new Set(['work_pc', 'big_desk', 'oak_desk']);
// Chair types that pair with desks
const CHAIR_TYPES = new Set(['chair', 'leather_chair', 'office_chair_exec', 'office_chair_mod', 'dining_chair', 'wooden_stool', 'metal_stool']);

const ObjectDefs = {
  chair:          { name: 'Chair',          w: 1, h: 1, passable: true },
  sofa_single:    { name: 'Sofa',           w: 1, h: 1 },
  sofa_double:    { name: 'Double Sofa',    w: 2, h: 1 },
  table:          { name: 'Table',          w: 4, h: 1 },
  filing_cabinet: { name: 'Filing Cabinet', w: 1, h: 1 },
  toilet:         { name: 'Toilet',         w: 1, h: 1 },
  bathroom_sink:  { name: 'Bathroom Sink',  w: 1, h: 1 },
  tv:             { name: 'TV',             w: 1, h: 1 },
  large_tv:       { name: 'Large TV',       w: 2, h: 1 },
  pool_table:     { name: 'Pool Table',     w: 3, h: 2 },
  bookshelf:      { name: 'Bookshelf',      w: 1, h: 1 },
  power_station:  { name: 'Power Station',  w: 3, h: 3, noRotate: true, infrastructure: true, powerOutput: 2000,  unit: 'W',    desc: 'Main power supply — 2kW output' },
  capacitor:      { name: 'Capacitor',      w: 1, h: 1, noRotate: true, infrastructure: true, powerBuffer: 500,   unit: 'W',    desc: 'Stores 500W — smooths power spikes' },
  radiator:       { name: 'Radiator',       w: 1, h: 1, infrastructure: true, heatOutput: 1.5,    unit: 'kW',   desc: 'Heats nearby area — needs hot water pipe' },
  tree:           { name: 'Tree',           w: 2, h: 2, noRotate: true },
  water_pump:     { name: 'Water Pump',     w: 3, h: 3, noRotate: true, infrastructure: true, waterOutput: 80,    unit: 'L/min', desc: 'Pressurizes water system — 80 L/min' },

  // ── Stage 2: Furniture ──
  big_desk:           { name: 'Big Desk',           w: 1, h: 2 },
  bookshelf_large:    { name: 'Large Bookshelf',    w: 2, h: 2 },
  leather_chair:      { name: 'Leather Chair',      w: 1, h: 1, passable: true },
  dining_chair:       { name: 'Dining Chair',       w: 1, h: 1, passable: true },
  dining_table:       { name: 'Dining Table',       w: 2, h: 3 },
  oak_desk:           { name: 'Oak Desk',           w: 2, h: 1 },
  oak_bookshelf:      { name: 'Oak Bookshelf',      w: 2, h: 2 },
  electrical_switch:  { name: 'Electrical Switch',  w: 1, h: 1, wallMount: true, passable: true },
  glass_window:       { name: 'Glass Window',       w: 1, h: 1, wallMount: true, passable: true },

  // ── Stage 2: DLC Furniture & Decor ──
  leather_sofa:       { name: 'Leather Sofa',       w: 2, h: 1 },
  coat_stand:         { name: 'Coat Stand',         w: 1, h: 2, noRotate: true },
  small_table:        { name: 'Small Table',        w: 2, h: 1 },
  wooden_stool:       { name: 'Wooden Stool',       w: 1, h: 1, noRotate: true, passable: true },
  wooden_table:       { name: 'Wooden Table',       w: 1, h: 1, noRotate: true },
  picnic_table:       { name: 'Picnic Table',       w: 3, h: 3, noRotate: true },
  oval_table:         { name: 'Oval Table',         w: 2, h: 2, noRotate: true },
  bookshelf_short:    { name: 'Short Bookshelf',    w: 2, h: 2 },
  foosball:           { name: 'Foosball Table',     w: 2, h: 2 },
  plant:              { name: 'Plant',              w: 1, h: 1, noRotate: true },
  plant_cactus:       { name: 'Cactus Plant',       w: 1, h: 1, noRotate: true },
  bush:               { name: 'Bush',               w: 1, h: 1, noRotate: true },
  tree_cactus:        { name: 'Cactus Tree',        w: 2, h: 2, noRotate: true },
  tree_sakura:        { name: 'Sakura Tree',        w: 2, h: 2, noRotate: true },
  tree_snowy:         { name: 'Snowy Pine',         w: 2, h: 2, noRotate: true },
  tree_spooky:        { name: 'Dead Tree',          w: 2, h: 2, noRotate: true },
  stone_fountain:     { name: 'Stone Fountain',     w: 2, h: 2, noRotate: true },
  office_chair_exec:  { name: 'Executive Chair',    w: 1, h: 1, passable: true },
  oak_table:          { name: 'Oak Table',          w: 3, h: 2 },
  window_classy:      { name: 'Classy Window',      w: 1, h: 1, wallMount: true },
  window_classy_large:{ name: 'Large Classy Window',w: 2, h: 1, wallMount: true },
  window_glass_large: { name: 'Large Glass Window', w: 2, h: 1, wallMount: true },

  // ── Stage 2: DLC2 Objects ──
  backup_generator:   { name: 'Backup Generator',   w: 3, h: 3, noRotate: true, infrastructure: true, powerOutput: 1000,  unit: 'W',    desc: 'Emergency 1kW — activates on power loss' },
  battery:            { name: 'Battery',            w: 1, h: 1, noRotate: true, infrastructure: true, powerBuffer: 2000,  unit: 'Wh',   desc: 'Stores 2kWh — UPS for critical systems' },
  solar_panel:        { name: 'Solar Panel',        w: 1, h: 2, infrastructure: true, powerOutput: 200,   unit: 'W',    desc: '200W peak — output varies with daylight' },
  fan:                { name: 'Fan',                w: 2, h: 2, noRotate: true, infrastructure: true, powerDraw: 50,  cooling: 2, desc: 'Cools nearby area — reduces server heat' },
  fire_alarm:         { name: 'Fire Alarm',         w: 1, h: 1, wallMount: true, infrastructure: true, powerDraw: 5, desc: 'Alerts staff on fire — needs power' },
  filing_cabinet_fancy:{ name: 'Fancy Filing Cabinet',w: 1, h: 1 },
  display_counter:    { name: 'Display Counter',    w: 3, h: 1 },
  dining_table_small: { name: 'Small Dining Table', w: 2, h: 2, noRotate: true },
  brown_sofa:         { name: 'Brown Sofa',         w: 2, h: 1 },
  fruit_apple_tree:   { name: 'Apple Tree',         w: 2, h: 2, noRotate: true },
  fruit_banana_tree:  { name: 'Banana Tree',        w: 2, h: 2, noRotate: true },
  fruit_orange_tree:  { name: 'Orange Tree',        w: 2, h: 2, noRotate: true },
  fruit_peach_tree:   { name: 'Peach Tree',         w: 2, h: 2, noRotate: true },
  fern_bush:          { name: 'Fern Bush',          w: 1, h: 1, noRotate: true },
  flower_begonias:    { name: 'Begonias',           w: 1, h: 1, noRotate: true },
  flower_heather:     { name: 'Heather',            w: 1, h: 1, noRotate: true },
  flower_hydrangeas:  { name: 'Hydrangeas',         w: 1, h: 1, noRotate: true },
  flower_rose:        { name: 'Rose Bush',          w: 1, h: 1, noRotate: true },
  flower_sunflower:   { name: 'Sunflower',          w: 1, h: 1, noRotate: true },

  metal_stool:        { name: 'Metal Stool',        w: 1, h: 1, noRotate: true, passable: true },
  outdoor_sprinkler:  { name: 'Sprinkler',          w: 1, h: 1, noRotate: true, passable: true },
  bare_tree:          { name: 'Bare Tree',          w: 2, h: 2, noRotate: true },
  blackboard:         { name: 'Blackboard',         w: 2, h: 1 },
  // ── Mod: Servers and More ──
  server:             { name: 'Server',             w: 1, h: 2, infrastructure: true, powerDraw: 300,   heatOutput: 250,  computeUnits: 8,  desc: '8 CU — needs power + ethernet + cooling' },
  network_switch:     { name: 'Network Switch',     w: 1, h: 1, noRotate: true, infrastructure: true, powerDraw: 30,    ports: 24,        throughput: 10,   unit: 'Gbps', desc: '24-port 10G switch — distributes network' },
  network_storage:    { name: 'Network Storage',    w: 1, h: 1, noRotate: true, infrastructure: true, powerDraw: 80,    storageCapacity: 16, unit: 'TB',   desc: '16 TB NAS — shared file storage' },
  server_parts_rack:  { name: 'Parts Rack',         w: 1, h: 1, noRotate: true, infrastructure: true, desc: 'Stores spare server components for repairs' },
  work_pc:            { name: 'Work PC',            w: 2, h: 1, fitToFootprint: true },
  printer_small:      { name: 'Small Printer',      w: 1, h: 1 },
  printer_large:      { name: 'Large Printer',      w: 1, h: 1 },
  office_chair_mod:   { name: 'Office Chair',       w: 1, h: 1, noRotate: true, passable: true },
};
