// Baked sprite render-offset overrides — ship with the app.
// Generated from the F3 debug editor (Ctrl+E to export and copy to clipboard).
// Paste the exported JSON between the braces below and commit.
//
// At runtime these are loaded first; localStorage (`pa_sprite_overrides`) is
// then layered on top, so dev-time nudges still override the baked values.
const BAKED_SPRITE_OVERRIDES = {
  "leather_sofa_r1": { "ox": -16, "oy": -32 },
  "leather_sofa_r2": { "ox": 0,   "oy": -32 },
  "leather_sofa_r3": { "ox": 16,  "oy": -32 },
  "sofa_double_r1":  { "ox": -16, "oy": -32 },
  "sofa_double_r3":  { "ox": 16,  "oy": -32 },
  "brown_sofa_r1":   { "ox": -16, "oy": -32 },
  "brown_sofa_r3":   { "ox": 16,  "oy": -32 },
  "table_r1":        { "ox": -24, "oy": -65 },
  "table_r3":        { "ox": 23,  "oy": -64 },
  "display_counter_r1": { "ox": -17, "oy": -47 },
  "display_counter_r3": { "ox": 16,  "oy": -49 },
  "work_pc_r0":      { "ox": 0,   "oy": 1 },
  "work_pc_r1":      { "ox": -17, "oy": -32 },
  "work_pc_r2":      { "ox": 0,   "oy": -32 },
  "work_pc_r3":      { "ox": 16,  "oy": -32 },
  "big_desk_r1":     { "ox": -31, "oy": -16 },
  "big_desk_r2":     { "ox": 1,   "oy": -63 },
  "big_desk_r3":     { "ox": 31,  "oy": -15 },
  "oak_desk_r1":     { "ox": -16, "oy": -32 },
  "oak_desk_r3":     { "ox": 16,  "oy": -32 },
  "office_chair_mod_r1": { "ox": -17, "oy": -14 },
  "office_chair_mod_r2": { "ox": 0,   "oy": -32 },
  "office_chair_mod_r3": { "ox": 16,  "oy": -15 },
  "blackboard_r1":   { "ox": -16, "oy": -32 },
  "blackboard_r3":   { "ox": 16,  "oy": -32 },
  "filing_cabinet_r1": { "ox": -16, "oy": -16 },
  "filing_cabinet_r2": { "ox": 0,   "oy": -31 },
  "filing_cabinet_r3": { "ox": 16,  "oy": -15 },
  "filing_cabinet_fancy_r0": { "ox": 0,   "oy": -15 },
  "filing_cabinet_fancy_r1": { "ox": -32, "oy": -15 },
  "filing_cabinet_fancy_r2": { "ox": 0,   "oy": -63 },
  "filing_cabinet_fancy_r3": { "ox": 16,  "oy": -14 },
  "printer_small_r1": { "ox": -16, "oy": -15 },
  "printer_small_r2": { "ox": 0,   "oy": -32 },
  "printer_small_r3": { "ox": 17,  "oy": -16 },
  "printer_large_r1": { "ox": -16, "oy": -14 },
  "printer_large_r2": { "ox": 0,   "oy": -32 },
  "printer_large_r3": { "ox": 17,  "oy": -16 },
  "bookshelf_short_r0": { "ox": 0, "oy": 4 },
  "bookshelf_short_r2": { "ox": 0, "oy": -45 },
  "oak_bookshelf_r1": { "ox": -32, "oy": -30 },
  "oak_bookshelf_r2": { "ox": 0,   "oy": -62 },
  "oak_bookshelf_r3": { "ox": 32,  "oy": -32 },
  "coffee_machine_r0": { "ox": 0,   "oy": -25 },
  "coffee_machine_r1": { "ox": -31, "oy": -16 },
  "coffee_machine_r2": { "ox": 0,   "oy": -63 },
  "coffee_machine_r3": { "ox": 6,   "oy": -16 },
  "drinking_fountain_r1": { "ox": -14, "oy": -16 },
  "drinking_fountain_r2": { "ox": 0,   "oy": -32 },
  "drinking_fountain_r3": { "ox": 14,  "oy": -15 },
  "bathroom_sink_r1": { "ox": -16, "oy": -15 },
  "bathroom_sink_r2": { "ox": 0,   "oy": -32 },
  "bathroom_sink_r3": { "ox": 16,  "oy": -16 },
  "large_tv_r1":     { "ox": -16, "oy": -32 },
  "large_tv_r3":     { "ox": 16,  "oy": -32 },
  "pool_table_r1":   { "ox": -33, "oy": -47 },
  "pool_table_r3":   { "ox": 32,  "oy": -48 },
  "foosball_r1":     { "ox": -32, "oy": -59 },
  "foosball_r3":     { "ox": 32,  "oy": -60 },
};
