// Helper for the common object-item shape in ToolbarData. Texture defaults to
// `objects/<id>.webp`; pass a third arg to override.
const obj = (id, name, texture) => ({
  id, name, cost: 0, objectType: id,
  texture: texture || `objects/${id}.webp`,
});

const ToolbarData = {
  foundations: {
    label: 'Foundations',
    mode: 'foundation',
    wallTypes: [
      { id: 'brick_wall', name: 'Brick', cost: 0, cell: CT.BRICK_WALL, icon: '▦' },
      { id: 'concrete_wall', name: 'Concrete', cost: 0, cell: CT.CONCRETE_WALL, icon: '▬' },
    ],
    floorCell: CT.CONCRETE_FLOOR,
    floorCost: 0,
  },
  materials: {
    label: 'Walls & Doors',
    mode: 'panel',
    tabs: [
      { name: 'Walls', items: [
        { id: 'brick_wall', name: 'Brick Wall', cost: 0, cell: CT.BRICK_WALL, texture: 'walls/Brick_Wall.webp' },
        { id: 'concrete_wall', name: 'Concrete Wall', cost: 0, cell: CT.CONCRETE_WALL, texture: 'walls/Concrete_Wall.webp' },
        { id: 'white_wall', name: 'White Wall', cost: 0, cell: CT.WHITE_WALL, texture: 'walls/White_Wall.webp' },
        { id: 'tiled_wall', name: 'Tiled Wall', cost: 0, cell: CT.TILED_WALL, texture: 'walls/Tiled_Wall.webp' },
        { id: 'yutani_wall', name: 'Hi-Tech', cost: 0, cell: CT.YUTANI_WALL, texture: 'walls/Wall (Yutani).webp' },
        { id: 'art_deco', name: 'Art Deco', cost: 0, cell: CT.ART_DECO_WALL, texture: 'walls/Wall (Art Deco).webp' },
        { id: 'oriental', name: 'Oriental', cost: 0, cell: CT.ORIENTAL_WALL, texture: 'walls/Wall (Oriental).webp' },
        { id: 'cushioned', name: 'Cushioned', cost: 0, cell: CT.CUSHIONED_WALL, texture: 'walls/Wall (Cushioned).webp' },
        { id: 'classy_burg', name: 'Classy\nBurgundy', cost: 0, cell: CT.CLASSY_BURGUNDY, texture: 'walls/Wall (Classy Burgundy).webp' },
        { id: 'classy_green', name: 'Classy\nGreen', cost: 0, cell: CT.CLASSY_GREEN, texture: 'walls/Wall Classy (Green).webp' },
        { id: 'classy_blue', name: 'Classy Blue', cost: 0, cell: CT.CLASSY_BLUE, texture: 'walls/Wall Classy (Blue Stripes).webp' },
        { id: 'fence', name: 'Fence', cost: 0, cell: CT.FENCE, texture: 'walls/Fence.webp' },
        { id: 'fence_grass', name: 'Fence\n(Grass)', cost: 0, cell: CT.FENCE_GRASS, texture: 'walls/Fence (Grass).webp' },
        { id: 'fence_bamboo', name: 'Fence\n(Bamboo)', cost: 0, cell: CT.FENCE_BAMBOO, texture: 'walls/Fence (Bamboo).webp' },
        { id: 'wooden_fence', name: 'Wooden\nFence', cost: 0, cell: CT.WOODEN_FENCE, texture: 'walls/Wooden Fence.webp' },
        { id: 'hedge', name: 'Hedge', cost: 0, cell: CT.HEDGE, texture: 'walls/Hedge.webp' },
        { id: 'white_picket', name: 'White\nPicket', cost: 0, cell: CT.WHITE_PICKET, texture: 'walls/White Picket Fence.webp' },
        { id: 'garden_wall', name: 'Garden Wall', cost: 0, cell: CT.GARDEN_WALL, texture: 'walls/Garden Wall.webp' },
        { id: 'perimeter_wall', name: 'Perimeter', cost: 0, cell: CT.PERIMETER_WALL, texture: 'walls/Perimeter_Wall.webp' },
        { id: 'barred_wall', name: 'Barred', cost: 0, cell: CT.BARRED_WALL, texture: 'walls/Barred_Wall.webp' },
        { id: 'rusty_wall', name: 'Rusty', cost: 0, cell: CT.RUSTY_WALL, texture: 'walls/Wall (Rusty).webp' },
        { id: 'slum_wall', name: 'Slum', cost: 0, cell: CT.SLUM_WALL, texture: 'walls/Wall (Slum).webp' },
        { id: 'derelict_wall', name: 'Derelict', cost: 0, cell: CT.DERELICT_WALL, texture: 'walls/Wall (Derelict).webp' },
        { id: 'overgrown_wall', name: 'Overgrown', cost: 0, cell: CT.OVERGROWN_WALL, texture: 'walls/Wall (Overgrown).webp' },
        { id: 'decayed_wall', name: 'Decayed', cost: 0, cell: CT.DECAYED_WALL, texture: 'walls/Wall (Decayed).webp' },
        { id: 'yellow_wall', name: 'Yellow', cost: 0, cell: CT.YELLOW_WALL, texture: 'walls/Wall (Yellow).webp' },
        { id: 'min_sec_wall', name: 'Min Sec', cost: 0, cell: CT.MIN_SEC_WALL, texture: 'walls/Wall (Min Sec).webp' },
        { id: 'med_sec_wall', name: 'Med Sec', cost: 0, cell: CT.MED_SEC_WALL, texture: 'walls/Wall (Med Sec).webp' },
        { id: 'max_sec_wall', name: 'Max Sec', cost: 0, cell: CT.MAX_SEC_WALL, texture: 'walls/Wall (Max Sec).webp' },
        { id: 'white_sec_wall', name: 'White Sec', cost: 0, cell: CT.WHITE_SEC_WALL, texture: 'walls/Wall (White).webp' },
        { id: 'cliff_edge_wall', name: 'Cliff Edge', cost: 0, cell: CT.CLIFF_EDGE_WALL, texture: 'walls/Cliff_Edge.webp' },
        { id: 'reclaimed_wood', name: 'Reclaimed\nWood', cost: 0, cell: CT.RECLAIMED_WOOD, texture: 'walls/Reclaimed Wood Wall.webp' },
        { id: 'bottle_wall', name: 'Bottle Wall', cost: 0, cell: CT.BOTTLE_WALL, texture: 'walls/Bottle Wall.webp' },
        { id: 'hay_bale', name: 'Hay Bale', cost: 0, cell: CT.HAY_BALE, texture: 'walls/Hay Bale Wall.webp' },
        { id: 'demolish_walls', name: 'Demolish\nWalls', cost: 0, demolishAction: 'walls', texture: 'icons/demolish.webp' },
      ]},
      { name: 'Doors', items: [
        { id: 'door', name: 'Door', cost: 0, cell: CT.DOOR, texture: 'doors/door.webp' },
        { id: 'staff_door', name: 'Staff Door', cost: 0, cell: CT.STAFF_DOOR, texture: 'doors/staff_door.webp' },
        { id: 'double_door', name: 'Double Door', cost: 0, cell: CT.DOUBLE_DOOR, pairCell: CT.DOUBLE_DOOR_R, placeWidth: 2, texture: 'doors/double_door.webp' },
        { id: 'secure_door', name: 'Secure Door', cost: 0, cell: CT.SECURE_DOOR, texture: 'doors/secure_door.webp' },
        { id: 'blue_door', name: 'Blue Door', cost: 0, cell: CT.BLUE_DOOR, texture: 'doors/blue_door.webp' },
        { id: 'red_door', name: 'Red Door', cost: 0, cell: CT.RED_DOOR, texture: 'doors/red_door.webp' },
        { id: 'orange_door', name: 'Orange Door', cost: 0, cell: CT.ORANGE_DOOR, texture: 'doors/orange_door.webp' },
        { id: 'double_staff_door', name: 'Double\nStaff Door', cost: 0, cell: CT.DOUBLE_STAFF_DOOR, pairCell: CT.DOUBLE_STAFF_DOOR_R, placeWidth: 2, texture: 'doors/double_staff_door.webp' },
        { id: 'house_door', name: 'House Door', cost: 0, cell: CT.HOUSE_DOOR, pairCell: CT.HOUSE_DOOR_R, placeWidth: 2, texture: 'doors/house_door.webp' },
        { id: 'demolish_doors', name: 'Demolish\nDoors', cost: 0, demolishAction: 'doors', texture: 'icons/demolish.webp' },
      ]},
    ],
  },
  flooring: {
    label: 'Flooring',
    mode: 'panel',
    tabs: [
      { name: 'Indoor', items: [
        { id: 'concrete_floor', name: 'Concrete', cost: 0, cell: CT.CONCRETE_FLOOR, texture: 'flooring/Concrete_Floor.webp' },
        { id: 'concrete_tile', name: 'Concrete\nTile', cost: 0, cell: CT.CONCRETE_TILE, texture: 'flooring/Concrete_Tile.webp' },
        { id: 'wooden_floor', name: 'Wood', cost: 0, cell: CT.WOODEN_FLOOR, texture: 'flooring/Wooden_Floor.webp' },
        { id: 'laminate', name: 'Laminate', cost: 0, cell: CT.LAMINATE, texture: 'flooring/Laminate_Flooring.webp' },
        { id: 'checkered', name: 'Checkered', cost: 0, cell: CT.CHECKERED_FLOOR, texture: 'flooring/Checkered_Floor.webp' },
        { id: 'metal_floor', name: 'Metal', cost: 0, cell: CT.METAL_FLOOR, texture: 'flooring/Metal_Floor.webp' },
        { id: 'iron_floor', name: 'Iron', cost: 0, cell: CT.IRON_FLOOR, texture: 'flooring/Iron_Floor.webp' },
        { id: 'cargo_floor', name: 'Cargo', cost: 0, cell: CT.CARGO_FLOOR, texture: 'flooring/Cargo_Floor.webp' },
        { id: 'carpet_red', name: 'Carpet\n(Red)', cost: 0, cell: CT.CARPET_RED, texture: 'flooring/Carpet_Red.webp' },
        { id: 'carpet_blue', name: 'Carpet\n(Blue)', cost: 0, cell: CT.CARPET_BLUE, texture: 'flooring/Carpet_Blue.webp' },
        { id: 'carpet_brown', name: 'Carpet\n(Brown)', cost: 0, cell: CT.CARPET_BROWN, texture: 'flooring/Carpet_Brown.webp' },
        { id: 'white_tiles', name: 'White Tiles', cost: 0, cell: CT.WHITE_TILES, texture: 'flooring/White_Tiles.webp' },
        { id: 'marble', name: 'Marble', cost: 0, cell: CT.MARBLE_TILES, texture: 'flooring/Marble_Tiles.webp' },
        { id: 'fancy_tiles', name: 'Fancy Tiles', cost: 0, cell: CT.FANCY_TILES, texture: 'flooring/Fancy_Tiles.webp' },
        { id: 'ceramic', name: 'Ceramic', cost: 0, cell: CT.CERAMIC_FLOOR, texture: 'flooring/CeramicFloor.webp' },
        { id: 'mosaic', name: 'Mosaic', cost: 0, cell: CT.MOSAIC_FLOOR, texture: 'flooring/Mosaic_Floor.webp' },
        { id: 'grate', name: 'Grate', cost: 0, cell: CT.GRATE_FLOOR, texture: 'flooring/Grate.webp' },
        { id: 'limestone', name: 'Limestone', cost: 0, cell: CT.LIMESTONE, texture: 'flooring/Limestone.webp' },
        { id: 'solaco', name: 'Solaco', cost: 0, cell: CT.SOLACO, texture: 'flooring/Solaco.webp' },
        { id: 'padded', name: 'Padded', cost: 0, cell: CT.PADDED, texture: 'flooring/Padded.webp' },
        { id: 'bamboo_floor', name: 'Bamboo', cost: 0, cell: CT.BAMBOO_FLOOR, texture: 'flooring/Bamboo.webp' },
        { id: 'clear_floor', name: 'Clear\nFloor', cost: 0, demolishAction: 'floors', texture: 'icons/demolish.webp' },
      ]},
      { name: 'Outdoor', items: [
        { id: 'grass', name: 'Grass', cost: 0, cell: CT.GRASS, texture: 'flooring/Grass.webp' },
        { id: 'field_grass', name: 'Field Grass', cost: 0, cell: CT.FIELD_GRASS, texture: 'flooring/Field_Grass.webp' },
        { id: 'flowery', name: 'Flowery\nField', cost: 0, cell: CT.FLOWERY_FIELD, texture: 'flooring/Flowery_Field.webp' },
        { id: 'grass_corner', name: 'Grass\nCorner', cost: 0, cell: CT.GRASS_CORNER, texture: 'flooring/Grass_Corner.webp' },
        { id: 'dirt', name: 'Dirt', cost: 0, cell: CT.DIRT, texture: 'flooring/Dirt.webp' },
        { id: 'mud', name: 'Mud', cost: 0, cell: CT.MUD, texture: 'flooring/Mud.webp' },
        { id: 'gravel', name: 'Gravel', cost: 0, cell: CT.GRAVEL, texture: 'flooring/Gravel.webp' },
        { id: 'paving', name: 'Paving Stone', cost: 0, cell: CT.PAVING_STONE, texture: 'flooring/Paving_Stone.webp' },
        { id: 'stone', name: 'Stone', cost: 0, cell: CT.STONE, texture: 'flooring/Stone.webp' },
        { id: 'sandstone', name: 'Sandstone', cost: 0, cell: CT.SANDSTONE, texture: 'flooring/Sandstone.webp' },
        { id: 'sand', name: 'Sand', cost: 0, cell: CT.SAND, texture: 'flooring/Sand_01.webp' },
        { id: 'road', name: 'Road', cost: 0, cell: CT.ROAD, texture: 'flooring/Road.webp' },
        { id: 'snow', name: 'Snow', cost: 0, cell: CT.SNOW, texture: 'flooring/Snow.webp' },
        { id: 'running_track', name: 'Running\nTrack', cost: 0, cell: CT.RUNNING_TRACK, texture: 'flooring/Running_Track.webp' },
        { id: 'water', name: 'Water', cost: 0, cell: CT.WATER, texture: 'flooring/Water.webp' },
        { id: 'dock_wooden', name: 'Wooden\nDock', cost: 0, cell: CT.DOCK_WOODEN, texture: 'flooring/Dock_Wooden.webp' },
        { id: 'cliff_edge_floor', name: 'Cliff Edge', cost: 0, cell: CT.CLIFF_EDGE_FLOOR, texture: 'flooring/Cliff_Edge.webp' },
        { id: 'clear_floor_out', name: 'Clear\nFloor', cost: 0, demolishAction: 'floors', texture: 'icons/demolish.webp' },
      ]},
    ],
  },
  rooms: {
    label: 'Rooms',
    mode: 'panel',
    tabs: [
      { name: 'Designate', items: [
        { id: 'room_office', name: 'Office', cost: 0, roomType: 'office',
          style: 'room-blue',
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="14" rx="1"/><path d="M12 7V3M8 7V5M16 7V5"/><circle cx="12" cy="14" r="2"/></svg>' },
        { id: 'room_server', name: 'Server\nRoom', cost: 0, roomType: 'server_room',
          style: 'room-green',
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="6" rx="1"/><rect x="3" y="13" width="18" height="6" rx="1"/><circle cx="7" cy="6" r="1"/><circle cx="7" cy="16" r="1"/><path d="M11 6h6M11 16h6"/></svg>' },
        { id: 'room_break', name: 'Break\nRoom', cost: 0, roomType: 'break_room',
          style: 'room-orange',
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M5 12a2 2 0 01-2-2V7h18v3a2 2 0 01-2 2M5 12v5a2 2 0 002 2h10a2 2 0 002-2v-5"/><path d="M19 7V5a2 2 0 00-2-2H7a2 2 0 00-2 2v2"/></svg>' },
        { id: 'room_bathroom', name: 'Bathroom', cost: 0, roomType: 'bathroom',
          style: 'room-blue',
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12h16v4a4 4 0 01-4 4H8a4 4 0 01-4-4v-4z"/><path d="M6 12V5a2 2 0 012-2h1"/><circle cx="16" cy="6" r="2"/></svg>' },
        { id: 'remove_room', name: 'Remove\nRoom', cost: 0, roomAction: 'remove', texture: 'icons/demolish.webp' },
      ]},
    ],
  },
  objects: {
    label: 'Objects',
    mode: 'objects',
    categories: [
      { name: 'Seating', items: [
        obj('chair', 'Chair'),
        obj('leather_chair', 'Leather\nChair'),
        obj('office_chair_exec', 'Executive\nChair'),
        obj('dining_chair', 'Dining\nChair'),
        obj('wooden_stool', 'Wooden\nStool'),
        obj('metal_stool', 'Metal Stool'),
        obj('sofa_single', 'Sofa'),
        obj('sofa_double', 'Double Sofa'),
        obj('leather_sofa', 'Leather\nSofa'),
        obj('brown_sofa', 'Brown Sofa'),
      ]},
      { name: 'Tables', items: [
        obj('table', 'Table'),
        obj('small_table', 'Small Table'),
        obj('wooden_table', 'Wooden\nTable'),
        obj('oval_table', 'Oval Table'),
        obj('oak_table', 'Oak Table'),
        obj('dining_table', 'Dining\nTable'),
        obj('dining_table_small', 'Small\nDining'),
        obj('picnic_table', 'Picnic\nTable'),
        obj('display_counter', 'Display\nCounter'),
      ]},
      { name: 'Office', items: [
        obj('work_pc', 'Work PC', 'objects/work_pc_combined.webp'),
        obj('big_desk', 'Big Desk'),
        obj('oak_desk', 'Oak Desk'),
        obj('office_chair_mod', 'Office Chair'),
        obj('blackboard', 'Blackboard'),
        obj('filing_cabinet', 'Filing\nCabinet'),
        obj('filing_cabinet_fancy', 'Fancy\nCabinet'),
        obj('printer_small', 'Small\nPrinter'),
        obj('printer_large', 'Large\nPrinter'),
      ]},
      { name: 'Storage', items: [
        obj('bookshelf', 'Bookshelf'),
        obj('bookshelf_large', 'Large\nBookshelf'),
        obj('bookshelf_short', 'Short\nBookshelf'),
        obj('oak_bookshelf', 'Oak\nBookshelf'),
        obj('coat_stand', 'Coat Stand'),
      ]},
      { name: 'Bathroom', items: [
        obj('toilet', 'Toilet'),
        obj('bathroom_sink', 'Bathroom\nSink'),
      ]},
      { name: 'Leisure', items: [
        obj('tv', 'TV'),
        obj('large_tv', 'Large TV'),
        obj('pool_table', 'Pool Table'),
        obj('foosball', 'Foosball'),
      ]},
      { name: 'Windows', items: [
        obj('glass_window', 'Glass\nWindow'),
        obj('window_classy', 'Classy\nWindow'),
        obj('window_classy_large', 'Large Classy\nWindow'),
        obj('window_glass_large', 'Large Glass\nPane'),
      ]},
      { name: 'Nature', items: [
        obj('tree', 'Tree'),
        obj('bare_tree', 'Bare Tree'),
        obj('tree_sakura', 'Sakura\nTree'),
        obj('tree_snowy', 'Snowy Pine'),
        obj('tree_spooky', 'Dead Tree'),
        obj('tree_cactus', 'Cactus Tree'),
        obj('fruit_apple_tree', 'Apple Tree'),
        obj('fruit_banana_tree', 'Banana\nTree'),
        obj('fruit_orange_tree', 'Orange\nTree'),
        obj('fruit_peach_tree', 'Peach Tree'),
        obj('bush', 'Bush'),
        obj('fern_bush', 'Fern Bush'),
        obj('plant', 'Plant'),
        obj('plant_cactus', 'Cactus\nPlant'),
        obj('flower_begonias', 'Begonias'),
        obj('flower_heather', 'Heather'),
        obj('flower_hydrangeas', 'Hydrangeas'),
        obj('flower_rose', 'Rose Bush'),
        obj('flower_sunflower', 'Sunflower'),
        obj('stone_fountain', 'Stone\nFountain'),
      ]},
    ],
  },
  staff: {
    label: 'Staff',
    mode: 'staff',
    categories: [
      { name: 'AI Agents', items: [
        { id: 'general', name: 'General\nAgent', cost: 0, workerType: 'general', texture: 'workers/teacher/front.webp' },
      ]},
    ],
  },
  utilities: {
    label: 'Utilities',
    mode: 'utilities',
    categories: [
      // ── Power ──
      { name: 'Power', items: [
        { id: 'power_cable', name: 'Power\nCable', cost: 0, utilityType: UT.POWER_CABLE,
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="#ffd600" stroke-width="2.5" stroke-linecap="round"><path d="M5 12h14"/><circle cx="3" cy="12" r="2" fill="#ffd600"/><circle cx="21" cy="12" r="2" fill="#ffd600"/></svg>' },
        { id: 'power_cable_heavy', name: 'Heavy\nPower', cost: 0, utilityType: UT.POWER_CABLE_HEAVY,
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="#ff8f00" stroke-width="4" stroke-linecap="round"><path d="M5 12h14"/><circle cx="3" cy="12" r="2.5" fill="#ff8f00"/><circle cx="21" cy="12" r="2.5" fill="#ff8f00"/></svg>' },
        { id: 'power_station_obj', name: 'Power\nStation', cost: 0, objectType: 'power_station', texture: 'objects/power_station.webp' },
        { id: 'backup_gen_obj', name: 'Backup\nGenerator', cost: 0, objectType: 'backup_generator', texture: 'objects/backup_generator.webp' },
        { id: 'solar_panel_obj', name: 'Solar\nPanel', cost: 0, objectType: 'solar_panel', texture: 'objects/solar_panel.webp' },
        { id: 'battery_obj', name: 'Battery', cost: 0, objectType: 'battery', texture: 'objects/battery.webp' },
        { id: 'capacitor_obj', name: 'Capacitor', cost: 0, objectType: 'capacitor', texture: 'objects/capacitor.webp' },
        { id: 'electrical_switch_obj', name: 'Electrical\nSwitch', cost: 0, objectType: 'electrical_switch', texture: 'objects/electrical_switch.webp' },
      ]},

      // ── Water ──
      { name: 'Water', items: [
        { id: 'water_pipe_small', name: 'Small\nPipe', cost: 0, utilityType: UT.WATER_PIPE_SMALL,
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="#00bcd4" stroke-width="2.5" stroke-linecap="round"><path d="M5 12h14"/><circle cx="3" cy="12" r="2" fill="#00bcd4"/><circle cx="21" cy="12" r="2" fill="#00bcd4"/></svg>' },
        { id: 'water_pipe_large', name: 'Large\nPipe', cost: 0, utilityType: UT.WATER_PIPE_LARGE,
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="#006064" stroke-width="5" stroke-linecap="round"><path d="M5 12h14"/><circle cx="3" cy="12" r="3" fill="#006064"/><circle cx="21" cy="12" r="3" fill="#006064"/></svg>' },
        { id: 'water_pump_obj', name: 'Water\nPump', cost: 0, objectType: 'water_pump', texture: 'objects/water_pump.webp' },
        { id: 'radiator_obj', name: 'Radiator', cost: 0, objectType: 'radiator', texture: 'objects/radiator.webp' },
        { id: 'outdoor_sprinkler_obj', name: 'Sprinkler', cost: 0, objectType: 'outdoor_sprinkler', texture: 'objects/outdoor_sprinkler.webp' },
      ]},

      // ── Network ──
      { name: 'Network', items: [
        { id: 'ethernet_cat5e', name: 'Cat 5e\n1 Gbps', cost: 0, utilityType: UT.ETHERNET_CAT5E,
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="#2196f3" stroke-width="2" stroke-linecap="round" stroke-dasharray="4 2"><path d="M5 12h14"/><circle cx="3" cy="12" r="2" fill="#2196f3"/><circle cx="21" cy="12" r="2" fill="#2196f3"/></svg>' },
        { id: 'ethernet_cat6', name: 'Cat 6\n10 Gbps', cost: 0, utilityType: UT.ETHERNET_CAT6,
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="#1565c0" stroke-width="2.5" stroke-linecap="round" stroke-dasharray="6 2"><path d="M5 12h14"/><circle cx="3" cy="12" r="2" fill="#1565c0"/><circle cx="21" cy="12" r="2" fill="#1565c0"/></svg>' },
        { id: 'ethernet_fiber', name: 'Fiber\n100 Gbps', cost: 0, utilityType: UT.ETHERNET_FIBER,
          svg: '<svg viewBox="0 0 24 24" fill="none" stroke="#e040fb" stroke-width="2" stroke-linecap="round" stroke-dasharray="2 3"><path d="M5 12h14"/><circle cx="3" cy="12" r="2" fill="#e040fb"/><circle cx="21" cy="12" r="2" fill="#e040fb"/></svg>' },
        { id: 'network_switch_obj', name: 'Network\nSwitch', cost: 0, objectType: 'network_switch', texture: 'objects/network_switch.webp' },
      ]},

      // ── Servers ──
      { name: 'Servers', items: [
        { id: 'server_obj', name: 'Server', cost: 0, objectType: 'server', texture: 'objects/server.webp' },
        { id: 'network_storage_obj', name: 'Network\nStorage', cost: 0, objectType: 'network_storage', texture: 'objects/network_storage.webp' },
        { id: 'server_parts_rack_obj', name: 'Parts Rack', cost: 0, objectType: 'server_parts_rack', texture: 'objects/server_parts_rack.webp' },
        { id: 'fan_obj', name: 'Cooling\nFan', cost: 0, objectType: 'fan', texture: 'objects/fan.webp' },
      ]},

      // ── Safety ──
      { name: 'Safety', items: [
        { id: 'fire_alarm_obj', name: 'Fire Alarm', cost: 0, objectType: 'fire_alarm', texture: 'objects/fire_alarm.webp' },
        { id: 'outdoor_sprinkler_safety', name: 'Sprinkler', cost: 0, objectType: 'outdoor_sprinkler', texture: 'objects/outdoor_sprinkler.webp' },
      ]},
    ],
  },
  deployment: { label: 'Deployment', items: [] },
  logistics: { label: 'Logistics', items: [] },
  clone: { label: 'Clone', mode: 'clone', items: [] },
  planning: { label: 'Planning', mode: 'planning', items: [] },
  red_1: { label: '---', items: [] },
  red_2: { label: '---', items: [] },
  red_3: { label: '---', items: [] },
  red_4: { label: '---', items: [] },
  reports: {
    label: 'Phone',
    mode: 'overlay',
    items: [],
  },
};
