// ── Utility Types (underground layer) ──
const UT = {
  EMPTY: 0,

  // ── Power ──
  POWER_CABLE: 1,         // Standard power line — 100W capacity
  POWER_CABLE_HEAVY: 2,   // Heavy-duty power line — 500W capacity (thick copper)
  POWER_SOURCE: 3,        // Generated by power_station / backup_generator / solar

  // ── Water ──
  WATER_PIPE_SMALL: 10,   // ½" pipe — 5 L/min flow
  WATER_PIPE_LARGE: 11,   // 2" pipe — 40 L/min flow (mains/trunk line)
  WATER_SOURCE: 12,       // Generated by water_pump

  // ── Network ──
  ETHERNET_CAT5E: 20,     // Cat 5e — 1 Gbps, up to 100m
  ETHERNET_CAT6: 21,      // Cat 6 — 10 Gbps, up to 55m
  ETHERNET_FIBER: 22,     // Fiber optic — 100 Gbps, unlimited
  NETWORK_SOURCE: 23,     // Generated by network_switch
};

const UtilityDefs = {
  // Power
  [UT.POWER_CABLE]:       { name: 'Power Cable',       color: '#ffd600', lineWidth: 2.5, dash: [],     capacity: 100,   unit: 'W',    desc: 'Standard 100W copper line' },
  [UT.POWER_CABLE_HEAVY]: { name: 'Heavy Power Cable', color: '#ff8f00', lineWidth: 4,   dash: [],     capacity: 500,   unit: 'W',    desc: 'Heavy-duty 500W trunk line' },
  [UT.POWER_SOURCE]:      { name: 'Power Source',      color: '#ffd600', lineWidth: 3,   dash: [],     capacity: 0,     unit: 'W',    desc: 'Distributes power to connected cables' },

  // Water
  [UT.WATER_PIPE_SMALL]:  { name: 'Small Water Pipe',  color: '#00bcd4', lineWidth: 2.5, dash: [],     capacity: 5,     unit: 'L/min', desc: '½" pipe — fixtures & appliances' },
  [UT.WATER_PIPE_LARGE]:  { name: 'Large Water Pipe',  color: '#006064', lineWidth: 5,   dash: [],     capacity: 40,    unit: 'L/min', desc: '2" trunk pipe — mains supply' },
  [UT.WATER_SOURCE]:      { name: 'Water Source',      color: '#00bcd4', lineWidth: 4,   dash: [],     capacity: 0,     unit: 'L/min', desc: 'Pump output node' },

  // Network
  [UT.ETHERNET_CAT5E]:    { name: 'Cat 5e Ethernet',   color: '#2196f3', lineWidth: 2,   dash: [4, 2], capacity: 1,     unit: 'Gbps', desc: '1 Gbps — basic office networking' },
  [UT.ETHERNET_CAT6]:     { name: 'Cat 6 Ethernet',    color: '#1565c0', lineWidth: 2.5, dash: [6, 2], capacity: 10,    unit: 'Gbps', desc: '10 Gbps — server room backbone' },
  [UT.ETHERNET_FIBER]:    { name: 'Fiber Optic',       color: '#e040fb', lineWidth: 2,   dash: [2, 3], capacity: 100,   unit: 'Gbps', desc: '100 Gbps — unlimited range, fragile' },
  [UT.NETWORK_SOURCE]:    { name: 'Network Source',    color: '#2196f3', lineWidth: 2,   dash: [],     capacity: 0,     unit: 'Gbps', desc: 'Switch uplink node' },
};
